from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__S3__Data         import Schema__AWS__S3__Bucket
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__S3__Data         import Schema__AWS__S3__Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__S3__Data         import Schema__AWS__S3__Object__Content
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__S3__Data         import Schema__AWS__S3__Object__Head
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__S3__Data         import Schema__AWS__S3__Put__Result
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__S3__Data         import Schema__AWS__S3__Delete__Result

from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__Request__Data__S3__List_Buckets
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__Request__Data__S3__List_Objects
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__Request__Data__S3__Get_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__Request__Data__S3__Put_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__Request__Data__S3__Head_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__Request__Data__S3__Delete_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__AWS__Request__S3__List_Buckets
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__AWS__Request__S3__List_Objects
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__AWS__Request__S3__Get_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__AWS__Request__S3__Put_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__AWS__Request__S3__Head_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Request__S3      import Schema__AWS__Request__S3__Delete_Object

from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__Response__Data__S3__List_Buckets
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__Response__Data__S3__List_Objects
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__Response__Data__S3__Get_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__Response__Data__S3__Put_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__Response__Data__S3__Head_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__Response__Data__S3__Delete_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__AWS__Response__S3__List_Buckets
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__AWS__Response__S3__List_Objects
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__AWS__Response__S3__Get_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__AWS__Response__S3__Put_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__AWS__Response__S3__Head_Object
from mgraph_ai_service_aws.schemas.aws.s3.Schema__AWS__Response__S3     import Schema__AWS__Response__S3__Delete_Object
